Background provider
EthWorks/useDapp pull request #39
Opened 2021-02-18 15:29 UTC by Marik-D

2021-02-18 15:46 UTC, sz-piotr commented on packages/core/src/hooks/useChainCalls.ts
> +export function useChainCall(call: ChainCall | false | undefined | '') {
```suggestion
type Falsy = false | 0 | "" | null | undefined 
export function useChainCall(call: ChainCall | Falsy) {
```

2021-02-18 19:48 UTC, marekkirejczyk commented on packages/core/src/providers/Providers.tsx
> +  1: 'https://mainnet.infura.io/v3/62687d1a985d4508b2b7a24827551934',
eee.... `id` in code?
Let's extract it to separate configuration file and use provider that by default not requires id.
Ethers have provider that work out of the box (EtherscanProvider I think).

Also:
Let's fill in urls for all test networks by default

2021-02-18 19:49 UTC, marekkirejczyk commented on packages/core/src/providers/Providers.tsx
> +        {props.backgroundChain && <BackgroundChainActivator chainId={props.backgroundChain} />}
Why Background? ReadOnly maybe?
BackgroundChainActivator -> ReadOnlyActivator

2021-02-18 19:51 UTC, marekkirejczyk commented on packages/example/src/index.tsx
> +    <Providers backgroundChain={1}>
`<Providers readOnlyChain={1}>`?

2021-02-18 19:51 UTC, marekkirejczyk requested changes
See comments

2021-02-22 08:17 UTC, marekkirejczyk approved these changes

2021-02-22 13:33 UTC, merged